<?php
require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../config/db.php';

require_role('admin');
$pdo = get_db_connection();

function csv_download(string $filename, array $headers, array $rows, string $report_type = 'seniors'): void {
	header('Content-Type: text/plain; charset=utf-8');
	header('Content-Disposition: attachment; filename="' . $filename . '"');
	header('Cache-Control: no-cache, must-revalidate');
	header('Expires: Sat, 26 Jul 1997 05:00:00 GMT');
	
	$out = fopen('php://output', 'w');
	
	// Add BOM for proper UTF-8 encoding in Excel
	fwrite($out, "\xEF\xBB\xBF");
	
	// Dynamic header based on report type
	$report_titles = [
		'seniors_official' => 'SOCIAL PENSION PROGRAM POTENTIAL LIST OF BENEFICIARIES',
		'seniors_full' => 'COMPLETE SENIORS DATA REPORT',
		'event_ranking' => 'EVENT PARTICIPATION RANKING REPORT',
		'deceased' => 'DECEASED SENIORS REPORT',
		'transferred' => 'TRANSFERRED SENIORS REPORT',
		'waiting' => 'WAITING SENIORS REPORT',
		'benefits' => 'BENEFITS MANAGEMENT REPORT',
		'barangays' => 'BARANGAYS LISTING REPORT',
		'attendance' => 'ATTENDANCE RECORDS REPORT'
	];
	
	$main_title = $report_titles[$report_type] ?? 'SENIORS DATA REPORT';
	
	// Add professional header information matching PDF format
	fwrite($out, str_repeat('=', 100) . "\n");
	fwrite($out, "\n");
	fwrite($out, "REPUBLIC OF THE PHILIPPINES\n");
	fwrite($out, "PROVINCE OF BUKIDNON\n");
	fwrite($out, "MUNICIPALITY OF MANOLO FORTICH\n");
	fwrite($out, "\n");
	fwrite($out, $main_title . "\n");
	fwrite($out, "\n");
	fwrite($out, "As of " . date('F j, Y') . "\n");
	fwrite($out, "Control Number: Manolo Fortich-" . date('Y') . "-" . str_pad(rand(1, 999), 3, '0', STR_PAD_LEFT) . "\n");
	fwrite($out, "\n");
	fwrite($out, str_repeat('=', 100) . "\n");
	fwrite($out, "\n");
	
	// Add column headers with proper formatting
	$formattedHeaders = array_map('strtoupper', $headers);
	$headerLine = implode("\t", $formattedHeaders);
	fwrite($out, $headerLine . "\n");
	
	// Add separator line
	$separatorLine = implode("\t", array_fill(0, count($headers), str_repeat('-', 15)));
	fwrite($out, $separatorLine . "\n");
	
	// Add data rows with proper formatting
	foreach ($rows as $r) { 
		$formattedRow = array_map(function($value) {
			// Clean and format data
			$value = trim($value);
			// Convert dates to proper format if they look like dates
			if (preg_match('/^\d{4}-\d{2}-\d{2}/', $value)) {
				$value = date('m/d/Y', strtotime($value));
			}
			return $value;
		}, array_values($r));
		$dataLine = implode("\t", $formattedRow);
		fwrite($out, $dataLine . "\n");
	}
	
	// Add professional footer information matching PDF format
	fwrite($out, "\n");
	fwrite($out, str_repeat('=', 100) . "\n");
	fwrite($out, "\n");
	fwrite($out, "REPORT SUMMARY\n");
	fwrite($out, "Generated on: " . date('F j, Y \a\t g:i A') . "\n");
	fwrite($out, "Total Records: " . count($rows) . "\n");
	fwrite($out, "Generated by: SeniorCare Information System\n");
	fwrite($out, "Municipality of Manolo Fortich, Bukidnon\n");
	fwrite($out, "\n");
	fwrite($out, str_repeat('=', 100) . "\n");
	
	fclose($out);
	exit;
}

function pdf_render(string $title, array $headers, array $rows, string $report_type = 'seniors'): void {
    // Enhanced PDF-friendly HTML with A4 print optimization and professional styling
    echo '<!doctype html><html><head><meta charset="utf-8"><title>' . htmlspecialchars($title) . '</title>';
    echo '<style>
        @page {
            size: A4;
            margin: 1.5cm 1cm;
        }
        * {
            box-sizing: border-box;
        }
        body {
            font-family: "Times New Roman", serif;
            margin: 0;
            padding: 0;
            color: #000;
            background: white;
            font-size: 11px;
            line-height: 1.3;
        }
        .header {
            text-align: center;
            margin-bottom: 25px;
            border-bottom: 3px solid #000;
            padding-bottom: 15px;
        }
        .logos {
            display: flex;
            justify-content: center;
            align-items: center;
            margin-bottom: 15px;
            gap: 20px;
        }
        .logo {
            width: 60px;
            height: 60px;
            border: 2px solid #000;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            overflow: hidden;
            background: white;
        }
        .logo img {
            width: 100%;
            height: 100%;
            object-fit: contain;
            border-radius: 50%;
        }
        .logo-left {
            background: white;
        }
        .logo-right {
            background: white;
        }
        .header-text {
            text-align: center;
            margin: 0 20px;
        }
        .header-text h1 {
            font-size: 14px;
            font-weight: bold;
            margin: 0;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        .header-text h2 {
            font-size: 12px;
            font-weight: bold;
            margin: 3px 0;
            text-transform: uppercase;
            letter-spacing: 0.3px;
        }
        .header-text h3 {
            font-size: 16px;
            font-weight: bold;
            margin: 8px 0;
            text-transform: uppercase;
            color: #1e40af;
            letter-spacing: 0.5px;
        }
        .report-info {
            text-align: center;
            margin: 15px 0;
            font-size: 11px;
            font-weight: bold;
        }
        .noprint {
            margin-bottom: 20px;
            text-align: center;
        }
        .noprint button {
            padding: 12px 24px;
            border: 2px solid #1e40af;
            border-radius: 6px;
            background: #1e40af;
            color: white;
            cursor: pointer;
            font-size: 14px;
            font-weight: bold;
            transition: all 0.3s ease;
        }
        .noprint button:hover {
            background: #1e3a8a;
            transform: translateY(-2px);
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 6px;
            margin-top: 10px;
            page-break-inside: auto;
            table-layout: fixed;
        }
        thead {
            display: table-header-group;
        }
        tbody tr {
            page-break-inside: avoid;
            page-break-after: auto;
        }
        th, td {
            border: 1px solid #000;
            padding: 1px 2px;
            text-align: left;
            vertical-align: middle;
            word-wrap: break-word;
            overflow: hidden;
        }
        th {
            background: #f5f5f5;
            font-weight: bold;
            text-align: center;
            font-size: 6px;
            text-transform: uppercase;
            letter-spacing: 0.1px;
        }
        td {
            font-size: 6px;
        }
        .number-col {
            text-align: center;
            width: 15px;
            font-weight: bold;
        }
        .name-col {
            width: 35px;
            font-weight: 500;
        }
        .barangay-col {
            width: 30px;
        }
        .age-col, .sex-col {
            text-align: center;
            width: 18px;
        }
        .osca-col {
            text-align: center;
            width: 30px;
            font-weight: bold;
        }
        .ext-col {
            width: 15px;
            text-align: center;
        }
        .civil-col {
            width: 25px;
        }
        .birthdate-col {
            width: 35px;
            text-align: center;
        }
        .remarks-col {
            width: 40px;
        }
        .health-col {
            width: 40px;
        }
        .purok-col {
            width: 25px;
        }
        .place-col {
            width: 40px;
        }
        .cellphone-col {
            width: 35px;
        }
        .life-col {
            width: 25px;
            text-align: center;
        }
        .category-col {
            width: 25px;
        }
        .footer {
            margin-top: 25px;
            text-align: center;
            font-size: 9px;
            border-top: 2px solid #000;
            padding-top: 8px;
            page-break-inside: avoid;
        }
        .footer p {
            margin: 2px 0;
            font-weight: bold;
        }
        @media print {
            .noprint { display: none; }
            body { 
                padding: 0;
                font-size: 8px;
            }
            .header { 
                page-break-inside: avoid;
                margin-bottom: 15px;
            }
            table {
                font-size: 5px;
                width: 100%;
            }
            th, td {
                padding: 1px 2px;
                font-size: 5px;
            }
            .number-col { width: 12px; }
            .name-col { width: 28px; }
            .barangay-col { width: 24px; }
            .age-col, .sex-col { width: 15px; }
            .osca-col { width: 24px; }
            .ext-col { width: 12px; }
            .civil-col { width: 20px; }
            .birthdate-col { width: 28px; }
            .remarks-col { width: 32px; }
            .health-col { width: 32px; }
            .purok-col { width: 20px; }
            .place-col { width: 32px; }
            .cellphone-col { width: 28px; }
            .life-col { width: 20px; }
            .category-col { width: 20px; }
        }
        @media screen {
            body {
                padding: 20px;
                max-width: 210mm;
                margin: 0 auto;
                box-shadow: 0 0 10px rgba(0,0,0,0.1);
            }
        }
    </style>';
    echo '</head><body>';
    
    echo '<div class="noprint">
        <button onclick="window.print()">🖨️ Print / Save as PDF</button>
    </div>';
    
    // Dynamic header based on report type
    $report_titles = [
        'seniors_official' => 'SOCIAL PENSION PROGRAM POTENTIAL LIST OF BENEFICIARIES',
        'seniors_full' => 'COMPLETE SENIORS DATA REPORT',
        'event_ranking' => 'EVENT PARTICIPATION RANKING REPORT',
        'deceased' => 'DECEASED SENIORS REPORT',
        'transferred' => 'TRANSFERRED SENIORS REPORT',
        'waiting' => 'WAITING SENIORS REPORT',
        'benefits' => 'BENEFITS MANAGEMENT REPORT',
        'barangays' => 'BARANGAYS LISTING REPORT',
        'attendance' => 'ATTENDANCE RECORDS REPORT'
    ];
    
    $main_title = $report_titles[$report_type] ?? 'SENIORS DATA REPORT';
    
    // Header with logos and official format
    echo '<div class="header">';
    echo '<div class="logos">';
    echo '<div class="logo logo-left"><img src="' . BASE_URL . '/images/logo.png" alt="DILG Logo" /></div>';
    echo '<div class="header-text">';
    echo '<h1>Republic of the Philippines</h1>';
    echo '<h2>Province of Bukidnon</h2>';
    echo '<h2>Municipality of Manolo Fortich</h2>';
    echo '<h3>' . $main_title . '</h3>';
    echo '</div>';
    echo '<div class="logo logo-right"><img src="' . BASE_URL . '/images/MANOLO FORTICH LOGO.png" alt="Manolo Fortich Logo" /></div>';
    echo '</div>';
    echo '<div class="report-info">';
    echo '<strong>As of ' . date('F j, Y') . '</strong><br>';
    echo '<strong>Control Number: Manolo Fortich-' . date('Y') . '-' . str_pad(rand(1, 999), 3, '0', STR_PAD_LEFT) . '</strong>';
    echo '</div>';
    echo '</div>';
    
    // Data table with improved styling
    echo '<table>';
    echo '<thead><tr>';
    echo '<th class="number-col">No.</th>';
    foreach ($headers as $h) { 
        $class = '';
        if (in_array($h, ['Last Name', 'First Name', 'Middle Name'])) $class = 'name-col';
        elseif ($h === 'Barangay') $class = 'barangay-col';
        elseif (in_array($h, ['Age', 'Sex'])) $class = 'age-col';
        elseif ($h === 'OSCA ID No') $class = 'osca-col';
        elseif ($h === 'Ext') $class = 'ext-col';
        elseif ($h === 'Civil Status') $class = 'civil-col';
        elseif ($h === 'Birthdate') $class = 'birthdate-col';
        elseif ($h === 'Remarks') $class = 'remarks-col';
        elseif ($h === 'Health Condition') $class = 'health-col';
        elseif ($h === 'Purok') $class = 'purok-col';
        elseif ($h === 'Place of Birth') $class = 'place-col';
        elseif ($h === 'Cellphone #') $class = 'cellphone-col';
        elseif ($h === 'Life Status') $class = 'life-col';
        elseif ($h === 'Category') $class = 'category-col';
        echo '<th class="' . $class . '">' . htmlspecialchars($h) . '</th>'; 
    }
    echo '</tr></thead><tbody>';
    
    $rowNum = 1;
    foreach ($rows as $r) {
        echo '<tr>';
        echo '<td class="number-col">' . $rowNum . '</td>';
        foreach ($headers as $i => $h) { 
            $value = (string)array_values($r)[$i] ?? '';
            $class = '';
            if (in_array($h, ['Last Name', 'First Name', 'Middle Name'])) $class = 'name-col';
            elseif ($h === 'Barangay') $class = 'barangay-col';
            elseif (in_array($h, ['Age', 'Sex'])) $class = 'age-col';
            elseif ($h === 'OSCA ID No') $class = 'osca-col';
            elseif ($h === 'Ext') $class = 'ext-col';
            elseif ($h === 'Civil Status') $class = 'civil-col';
            elseif ($h === 'Birthdate') $class = 'birthdate-col';
            elseif ($h === 'Remarks') $class = 'remarks-col';
            elseif ($h === 'Health Condition') $class = 'health-col';
            elseif ($h === 'Purok') $class = 'purok-col';
            elseif ($h === 'Place of Birth') $class = 'place-col';
            elseif ($h === 'Cellphone #') $class = 'cellphone-col';
            elseif ($h === 'Life Status') $class = 'life-col';
            elseif ($h === 'Category') $class = 'category-col';
            echo '<td class="' . $class . '">' . htmlspecialchars($value) . '</td>'; 
        }
        echo '</tr>';
        $rowNum++;
    }
    echo '</tbody></table>';
    
    // Footer with enhanced styling
    echo '<div class="footer">';
    echo '<p><strong>Generated on:</strong> ' . date('F j, Y \a\t g:i A') . '</p>';
    echo '<p><strong>Total Records:</strong> ' . count($rows) . '</p>';
    echo '<p><strong>Municipality of Manolo Fortich, Bukidnon</strong></p>';
    echo '</div>';
    
    echo '</body></html>';
    exit;
}

function dataset_query(PDO $pdo, string $dataset): array {
    switch ($dataset) {
        case 'seniors_full':
            $headers = ['Last Name','First Name','Middle Name','Ext','Barangay','Age','Sex','Civil Status','Birthdate','OSCA ID','Remarks','Health Condition','Purok','Place of Birth','Cellphone','Life Status','Category','Validation Status','Validated'];
            $sql = "SELECT last_name, first_name, COALESCE(middle_name,'') AS middle_name, COALESCE(ext_name,'') AS ext_name, barangay, age,
                    sex, civil_status, date_of_birth, osca_id_no, COALESCE(remarks,'') AS remarks, COALESCE(health_condition,'') AS health_condition,
                    COALESCE(purok,'') AS purok, COALESCE(place_of_birth,'') AS place_of_birth, COALESCE(cellphone,'') AS cellphone,
                    life_status, category, COALESCE(validation_status,'') AS validation_status, COALESCE(validation_date,'') AS validation_date
                    FROM seniors ORDER BY last_name, first_name";
            break;
        case 'seniors_official':
            $headers = ['Last Name','First Name','Middle Name','Ext','Barangay','Age','Sex','Civil Status','Birthdate','OSCA ID No','Remarks','Health Condition','Purok','Place of Birth','Cellphone #','Life Status','Category'];
            $sql = "SELECT last_name, first_name, COALESCE(middle_name,'') AS middle_name, COALESCE(ext_name,'') AS ext_name, barangay, age,
                    sex, civil_status, date_of_birth, osca_id_no, COALESCE(remarks,'') AS remarks, COALESCE(health_condition,'') AS health_condition,
                    COALESCE(purok,'') AS purok, COALESCE(place_of_birth,'') AS place_of_birth, COALESCE(cellphone,'') AS cellphone,
                    life_status, category
                    FROM seniors WHERE life_status='living' ORDER BY barangay, last_name, first_name";
            break;
        case 'event_ranking':
            $headers = ['Last Name','First Name','Barangay','Events Joined'];
            $sql = "SELECT s.last_name, s.first_name, s.barangay, COUNT(a.id) AS events_joined
                    FROM seniors s LEFT JOIN attendance a ON a.senior_id=s.id
                    GROUP BY s.id ORDER BY events_joined DESC, s.last_name, s.first_name";
            break;
        case 'deceased':
            $headers = ['Last Name','First Name','Middle Name','Ext','Barangay','Age','Sex','Civil Status','Birthdate','OSCA ID','Remarks','Health Condition','Purok','Place of Birth','Cellphone','Category','Validation Status','Validated'];
            $sql = "SELECT last_name, first_name, COALESCE(middle_name,'') AS middle_name, COALESCE(ext_name,'') AS ext_name, barangay, age,
                    sex, civil_status, date_of_birth, osca_id_no, COALESCE(remarks,'') AS remarks, COALESCE(health_condition,'') AS health_condition,
                    COALESCE(purok,'') AS purok, COALESCE(place_of_birth,'') AS place_of_birth, COALESCE(cellphone,'') AS cellphone,
                    category, COALESCE(validation_status,'') AS validation_status, COALESCE(validation_date,'') AS validation_date
                    FROM seniors WHERE life_status='deceased' ORDER BY last_name, first_name";
            break;
        case 'transferred':
            $headers = ['First Name','Middle Name','Last Name','Age','New Address','Transfer Date','Transfer Reason'];
            $sql = "SELECT s.first_name, COALESCE(s.middle_name,'') AS middle_name, s.last_name, s.age,
                    COALESCE(st.new_address, s.barangay) AS new_address,
                    COALESCE(st.effective_date, s.created_at) AS transfer_date,
                    COALESCE(st.transfer_reason,'Not specified') AS transfer_reason
                    FROM seniors s
                    LEFT JOIN (
                        SELECT t.* FROM senior_transfers t
                        INNER JOIN (
                            SELECT senior_id, MAX(id) AS max_id FROM senior_transfers GROUP BY senior_id
                        ) m ON t.id = m.max_id
                    ) st ON s.id = st.senior_id
                    LEFT JOIN senior_transfers st_any ON st_any.senior_id = s.id
                    WHERE (s.category='transferred' OR st_any.id IS NOT NULL)
                    ORDER BY s.last_name, s.first_name";
            break;
        case 'waiting':
            $headers = ['Last Name','First Name','Middle Name','Ext','Barangay','Age','Sex','Civil Status','Birthdate','OSCA ID','Remarks','Health Condition','Purok','Place of Birth','Cellphone','Life Status','Category','Validation Status','Validated'];
            $sql = "SELECT last_name, first_name, COALESCE(middle_name,'') AS middle_name, COALESCE(ext_name,'') AS ext_name, barangay, age,
                    sex, COALESCE(civil_status,'') AS civil_status, date_of_birth, osca_id_no, COALESCE(remarks,'') AS remarks,
                    COALESCE(health_condition,'') AS health_condition, COALESCE(purok,'') AS purok, COALESCE(place_of_birth,'') AS place_of_birth,
                    COALESCE(cellphone,'') AS cellphone, life_status, category, COALESCE(validation_status,'') AS validation_status,
                    COALESCE(validation_date,'') AS validation_date
                    FROM seniors WHERE life_status='living' AND category='waiting' ORDER BY created_at DESC";
            break;
        case 'benefits':
            $headers = ['OSCA ID','Name','Age','Gender','Barangay','Category','SP Q1','SP Q2','SP Q3','SP Q4','Octogenarian','Nonagenarian','Centenarian','Financial Asst','Burial Asst'];
            $sql = "SELECT s.osca_id_no,
                           CONCAT(COALESCE(s.last_name,''), ', ', COALESCE(s.first_name,''), ' ', COALESCE(s.middle_name,'')) AS name,
                           s.age,
                           s.sex AS gender,
                           s.barangay,
                           s.category,
                           MAX(CASE WHEN br.benefit_type='sp_q1' THEN br.received END) AS sp_q1,
                           MAX(CASE WHEN br.benefit_type='sp_q2' THEN br.received END) AS sp_q2,
                           MAX(CASE WHEN br.benefit_type='sp_q3' THEN br.received END) AS sp_q3,
                           MAX(CASE WHEN br.benefit_type='sp_q4' THEN br.received END) AS sp_q4,
                           MAX(CASE WHEN br.benefit_type='octogenarian' THEN br.received END) AS octogenarian,
                           MAX(CASE WHEN br.benefit_type='nonagenarian' THEN br.received END) AS nonagenarian,
                           MAX(CASE WHEN br.benefit_type='centenarian' THEN br.received END) AS centenarian,
                           MAX(CASE WHEN br.benefit_type='financial_asst' THEN br.received END) AS financial_asst,
                           MAX(CASE WHEN br.benefit_type='burial_asst' THEN br.received END) AS burial_asst
                    FROM seniors s
                    LEFT JOIN benefit_records br ON br.senior_id = s.id
                    WHERE s.life_status='living'
                    GROUP BY s.id
                    ORDER BY s.barangay, s.last_name, s.first_name";
            break;
        case 'barangays':
            $headers = ['ID','Barangay Name','Created'];
            $sql = "SELECT id, name, created_at FROM barangays ORDER BY name ASC";
            break;
        case 'attendance':
            $headers = ['ID','Senior Last Name','Senior First Name','Event Title','Event Date','Marked At'];
            $sql = "SELECT a.id, s.last_name, s.first_name, e.title, e.event_date, a.marked_at
		FROM attendance a
		JOIN seniors s ON s.id = a.senior_id
		JOIN events e ON e.id = a.event_id
                    ORDER BY e.event_date DESC, a.marked_at DESC";
            break;
        default:
            $headers = ['ID','First Name','Middle Name','Last Name','Age','Barangay','Benefits Received','Life Status','Category'];
            $sql = "SELECT id, first_name, middle_name, last_name, age, barangay, benefits_received, life_status, category FROM seniors ORDER BY last_name, first_name";
    }
    $stmt = $pdo->query($sql);
    $rows = $stmt ? $stmt->fetchAll(PDO::FETCH_ASSOC) : [];
    return [$headers, $rows];
}

$dataset = $_GET['dataset'] ?? '';
$format = $_GET['format'] ?? '';
if ($dataset !== '' && $format !== '') {
    list($headers, $rows) = dataset_query($pdo, $dataset);
    $basename = $dataset . '_' . date('Ymd_His');
    if ($format === 'csv') {
        csv_download($basename . '.csv', $headers, $rows, $dataset);
    } elseif ($format === 'pdf') {
        pdf_render(strtoupper(str_replace('_',' ', $dataset)) . ' Report', $headers, $rows, $dataset);
    }
}

?>
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Reports & Analytics | SeniorCare Information System</title>
	<link rel="stylesheet" href="<?= BASE_URL ?>/assets/government-portal.css">
</head>
<body>
	<?php include __DIR__ . '/../partials/sidebar_admin.php'; ?>
	<main class="content">
		<header class="content-header">
			<h1 class="content-title">Reports & Analytics</h1>
			<p class="content-subtitle">Generate and download system reports</p>
		</header>
		
		<div class="content-body">
			<div class="grid grid-2">
				<div class="card">
					<div class="card-header">
						<h2 class="card-title">
							<i class="fas fa-download"></i>
							Data Export
						</h2>
                        <p class="card-subtitle">Download system data as CSV or PDF</p>
					</div>
					<div class="card-body">
						<div class="report-options">
                            <div style="border: 2px solid #1e40af; padding: 20px; margin-bottom: 20px; border-radius: 8px; background: #f8fafc;">
                                <div class="mb-2"><strong style="color: #1e40af; font-size: 16px;">📋 All Seniors Data Reports (Official Government Format)</strong></div>
                                <p style="font-size: 12px; color: #64748b; margin: 5px 0;">Complete seniors data with official government headers, logos, and formatting</p>
                                <div style="margin-top: 15px;">
                                    <a href="?dataset=seniors_official&format=csv" class="button primary" style="margin-right: 10px;">📊 CSV Export</a>
                                    <a href="?dataset=seniors_official&format=pdf" class="button secondary">📄 PDF Report</a>
                                </div>
                            </div>
                            <div style="border: 2px solid #1e40af; padding: 20px; margin-bottom: 20px; border-radius: 8px; background: #f8fafc;">
                                <div class="mb-2"><strong style="color: #1e40af; font-size: 16px;">📊 Event Participation Rankings</strong></div>
                                <p style="font-size: 12px; color: #64748b; margin: 5px 0;">Senior citizens ranked by event participation and engagement</p>
                                <div style="margin-top: 15px;">
                                    <a href="?dataset=event_ranking&format=csv" class="button primary" style="margin-right: 10px;">📊 CSV Export</a>
                                    <a href="?dataset=event_ranking&format=pdf" class="button secondary">📄 PDF Report</a>
                                </div>
                            </div>
                            <div style="border: 2px solid #1e40af; padding: 20px; margin-bottom: 20px; border-radius: 8px; background: #f8fafc;">
                                <div class="mb-2"><strong style="color: #1e40af; font-size: 16px;">💀 Deceased Seniors</strong></div>
                                <p style="font-size: 12px; color: #64748b; margin: 5px 0;">Records of deceased senior citizens with complete information</p>
                                <div style="margin-top: 15px;">
                                    <a href="?dataset=deceased&format=csv" class="button primary" style="margin-right: 10px;">📊 CSV Export</a>
                                    <a href="?dataset=deceased&format=pdf" class="button secondary">📄 PDF Report</a>
                                </div>
                            </div>
                            <div style="border: 2px solid #1e40af; padding: 20px; margin-bottom: 20px; border-radius: 8px; background: #f8fafc;">
                                <div class="mb-2"><strong style="color: #1e40af; font-size: 16px;">🚚 Transferred Seniors</strong></div>
                                <p style="font-size: 12px; color: #64748b; margin: 5px 0;">Senior citizens who have transferred to other locations</p>
                                <div style="margin-top: 15px;">
                                    <a href="?dataset=transferred&format=csv" class="button primary" style="margin-right: 10px;">📊 CSV Export</a>
                                    <a href="?dataset=transferred&format=pdf" class="button secondary">📄 PDF Report</a>
                                </div>
                            </div>
                            <div style="border: 2px solid #1e40af; padding: 20px; margin-bottom: 20px; border-radius: 8px; background: #f8fafc;">
                                <div class="mb-2"><strong style="color: #1e40af; font-size: 16px;">⏳ Waiting Seniors</strong></div>
                                <p style="font-size: 12px; color: #64748b; margin: 5px 0;">Senior citizens awaiting validation and approval</p>
                                <div style="margin-top: 15px;">
                                    <a href="?dataset=waiting&format=csv" class="button primary" style="margin-right: 10px;">📊 CSV Export</a>
                                    <a href="?dataset=waiting&format=pdf" class="button secondary">📄 PDF Report</a>
                                </div>
                            </div>
                            <div style="border: 2px solid #1e40af; padding: 20px; margin-bottom: 20px; border-radius: 8px; background: #f8fafc;">
                                <div class="mb-2"><strong style="color: #1e40af; font-size: 16px;">💰 Benefits Management</strong></div>
                                <p style="font-size: 12px; color: #64748b; margin: 5px 0;">Comprehensive benefits tracking and management reports</p>
                                <div style="margin-top: 15px;">
                                    <a href="?dataset=benefits&format=csv" class="button primary" style="margin-right: 10px;">📊 CSV Export</a>
                                    <a href="?dataset=benefits&format=pdf" class="button secondary">📄 PDF Report</a>
                                </div>
                            </div>
                            <div style="border: 2px solid #1e40af; padding: 20px; margin-bottom: 20px; border-radius: 8px; background: #f8fafc;">
                                <div class="mb-2"><strong style="color: #1e40af; font-size: 16px;">🏘️ Barangays</strong></div>
                                <p style="font-size: 12px; color: #64748b; margin: 5px 0;">Complete listing of all barangays in the municipality</p>
                                <div style="margin-top: 15px;">
                                    <a href="?dataset=barangays&format=csv" class="button primary" style="margin-right: 10px;">📊 CSV Export</a>
                                    <a href="?dataset=barangays&format=pdf" class="button secondary">📄 PDF Report</a>
                                </div>
                            </div>
                            <div style="border: 2px solid #1e40af; padding: 20px; margin-bottom: 20px; border-radius: 8px; background: #f8fafc;">
                                <div class="mb-2"><strong style="color: #1e40af; font-size: 16px;">📅 Attendance Records</strong></div>
                                <p style="font-size: 12px; color: #64748b; margin: 5px 0;">Event attendance tracking and participation records</p>
                                <div style="margin-top: 15px;">
                                    <a href="?dataset=attendance&format=csv" class="button primary" style="margin-right: 10px;">📊 CSV Export</a>
                                    <a href="?dataset=attendance&format=pdf" class="button secondary">📄 PDF Report</a>
                                </div>
                            </div>
						</div>
					</div>
				</div>
				
				<!-- Quick Statistics card removed as requested -->
			</div>
		</div>
	</main>
</body>
</html>


